version: "3.8"
services:
  redis:
    image: redis:7
    ports:
      - "6379:6379"
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: lkstream
      POSTGRES_PASSWORD: lkstream
      POSTGRES_DB: lkstream
    ports:
      - "5432:5432"
